[project]
name = "similarity"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "annoy>=1.17.3",
    "msgspec>=0.18.6",
    "numpy>=1.26.4",
    "sentence-transformers>=3.1.1",
    "torch>=2.4.1",
]
